name: "Test build"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.5", "3.6", "3.7", "3.8"]
        exclude:
          - platform: "macos-latest"
            python-version: "3.5"
          - platform: "macos-latest"
            python-version: "3.7"
          - platform: "windows-latest"
            python-version: "3.6"
          - platform: "windows-latest"
            python-version: "3.7"
        # platform: ["windows-latest"]
        # python-version: ["3.5", "3.6", "3.7", "3.8"]

    runs-on: "${{ matrix.platform }}"

    steps:
      - uses: "actions/checkout@v2"

      - name: "get conda"
        uses: "goanpeca/setup-miniconda@v1"
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: "install most dependencies"
        shell: "bash -l {0}"
        run: |
          conda env list
          conda update -n base -c defaults conda
          conda install numpy pandas pytest flake8
          pip install scikit-hep-testdata
          conda list

      - name: "install Awkward"
        shell: "bash -l {0}"
        run: |
          conda env list
          pip install awkward1
          conda list

      - name: "install XRootD"
        if: "${{ matrix.python-version != 3.5  &&  !contains(matrix.platform, 'macos')  &&  !contains(matrix.platform, 'windows') }}"
        shell: "bash -l {0}"
        run: |
          conda env list
          conda install xrootd
          conda list

      - name: "flake8"
        shell: "bash -l {0}"
        run: python -m flake8

      - name: "pytest"
        shell: "bash -l {0}"
        run: python -m pytest -vv tests
