name: "Test build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: "actions/checkout@v2"

      - name: "environment for ${{ matrix.python-version }}"
        run: |
          eval "$(conda shell.bash hook)"
          conda create -n testing python=${{ matrix.python-version }}
          conda config --add channels conda-forge
          conda info

      - name: "install most dependencies"
        run: |
          eval "$(conda shell.bash hook)"
          conda activate testing
          conda env list
          conda install numpy pandas pytest flake8
          pip install scikit-hep-testdata
          conda list

      - name: "install Awkward"
        run: |
          eval "$(conda shell.bash hook)"
          conda activate testing
          conda env list
          pip install awkward1
          conda list

      - name: "install XRootD"
        if: "${{ matrix.python-version != 3.5 }}"
        run: |
          eval "$(conda shell.bash hook)"
          conda activate testing
          conda env list
          conda install xrootd
          conda list

      - name: "flake8"
        run: |
          eval "$(conda shell.bash hook)"
          conda activate testing
          conda env list
          python -m flake8

      - name: "pytest"
        run: |
          eval "$(conda shell.bash hook)"
          conda activate testing
          conda env list
          python -m pytest -vv tests
