name: "Test build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: "actions/checkout@v2"

      - name: "get conda"
        uses: "goanpeca/setup-miniconda@v1"
        with:
          auto-update-conda: true

      - name: "environment for ${{ matrix.python-version }}"
        run: |
          conda create -n testing python=${{ matrix.python-version }}
          conda config --add channels conda-forge
          conda info

      - name: "install most dependencies"
        run: |
          conda activate testing
          conda env list
          conda install numpy pandas pytest flake8
          pip install scikit-hep-testdata
          conda list

      - name: "install Awkward"
        run: |
          conda activate testing
          conda env list
          pip install awkward1
          conda list

      - name: "install XRootD"
        if: "${{ matrix.python-version != 3.5 }}"
        run: |
          conda activate testing
          conda env list
          conda install xrootd
          conda list

      - name: "flake8"
        run: |
          conda activate testing
          conda env list
          python -m flake8

      - name: "pytest"
        run: |
          conda activate testing
          conda env list
          python -m pytest -vv tests
