name: "Test build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    runs-on: "${{ matrix.platform }}"

    steps:
      - uses: "actions/checkout@v2"

      - name: "environment for ${{ matrix.python-version }}"
        run: |
          ${CONDA}/bin/conda create -n testing python=${{ matrix.python-version }}
          ${CONDA}/bin/conda config --add channels conda-forge
          ${CONDA}/bin/conda info

      - name: "install most dependencies"
        run: |
          source ${CONDA}/bin/activate testing
          conda env list
          conda install numpy pandas pytest flake8
          pip install scikit-hep-testdata
          conda list

